### ISSUE TITLE
missing protocols

### ISSUE THREAD

**Issue by jeromedoyle** [jsvisa/elixir_talk#14]
Need to add `def parse(<<"BURIED\r\n", rest :: binary>>),          do: {:ok, :buried, rest}` line to lib/elixir_talk/protocol.ex

**Comment by jeromedoyle** [comment]
Same thing for kick_job. Seems to be missing `def parse(<<"KICKED\r\n", rest :: binary>>),          do: {:ok, :kicked, rest}`

**Comment by jsvisa** [comment]
@jeromedoyle fixed in #15 and thanks
